"use client";
import "./globals.css";
import Sidebar from "@/app/component/sidebar/Appbar";
import { Poppins } from "next/font/google";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { usePathname } from "next/navigation";
import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
const theme = createTheme({
  typography: {
    allVariants: {
      fontFamily: "Poppins",
      textTransform: "none",
      fontWeight: "300",
      fontSize: 16,
    },
  },
});

const disableSidebar = [
  {
    pathname: '/Payment/Complete'
  }
]



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const sidebarRender = () => {
    if (disableSidebar.filter(
      function (data) { return data.pathname === pathname }).length) {
      return null

    } else {
      return (<Sidebar />)
    }
  }

  return (
    <html lang="en">
      <title>Hotel Booking</title>
      <meta name='description' content='Hotel Booking' />
      <body className={poppins.className}>
        <ThemeProvider theme={theme}>
          <div className="flex h-screen w-full bg-white">
            {sidebarRender()}
            <div
              className="flex flex-col w-full h-full"
              style={{ marginLeft: "10rem" }}
            >
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
